feat: automate prod deployments (#353)
issue #338

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -94,14 +94,26 @@ jobs:
           cd server
           ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=br.com.tasknoteapp:server -Dsonar.coverage.jacoco.xmlReportPaths=target/coverage-reports/merged-test-report/jacoco.xml -Dsonar.exclusions=**/config/**,**/entity/**,**/exception/**,**/filter/**,**/**Builder*,**/RestExceptionEndpoint.*,**/JavaApiApiApplication.*
 
-  image-promotion:
-    name: Docker image promotion
+  image-promotion-and-deploy:
+    name: Image promotion and deployment
     runs-on: ubuntu-latest
+    env:
+      DEPLOY_DOMAIN: ${{ vars.DEPLOY_DOMAIN }}
+      GHCR_USERNAME: ${{ vars.GHCR_USERNAME }}
+      GHCR_PASSWORD: ${{ secrets.GHCR_PASSWORD }}
+      API_KEY: ${{ secrets.DOKPLOY_API_KEY }}
+      SERVER_APPID: ${{ secrets.PROD_API_CLIENT_ID }}
+      CLIENT_APPID: ${{ secrets.PROD_WEB_CLIENT_ID }}
     strategy:
       matrix:
-        image:
-          - service: server
-          - service: client
+        name: [server, client]
+        include:
+          - name: server
+            health_check_url: "${{ vars.API_PROD_URL }}/actuator/health"
+            app_id: ${SERVER_APPID}
+          - name: client
+            health_check_url: "${{ vars.CLIENT_PROD_URL }}/"
+            app_id: ${CLIENT_APPID}
     steps:
       - uses: docker/login-action@v3
         name: Login to GitHub Container Registry
@@ -111,17 +123,94 @@ jobs:
           password: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Pull image with source tag
-        run: docker pull ghcr.io/ricardo-campos-org/react-typescript-todolist/${{ matrix.image.service }}:candidate
+        run: docker pull ghcr.io/ricardo-campos-org/react-typescript-todolist/${{ matrix.name }}:candidate
 
       - name: Extract PR number using docker inspect
         id: inspect
         run: |
-          SOURCE_PR=$(docker inspect ghcr.io/ricardo-campos-org/react-typescript-todolist/${{ matrix.image.service }}:candidate | jq -r '.[0].Config.Env[] | select(startswith("SOURCE_PR="))' | sed -n 's/SOURCE_PR=\(v[0-9]*\).*/\1/p')
+          SOURCE_PR=$(docker inspect ghcr.io/ricardo-campos-org/react-typescript-todolist/${{ matrix.name }}:candidate | jq -r '.[0].Config.Env[] | select(startswith("SOURCE_PR="))' | sed -n 's/SOURCE_PR=\(v[0-9]*\).*/\1/p')
           echo "SOURCE_PR=$SOURCE_PR" >> $GITHUB_ENV
           echo "source_pr=$SOURCE_PR" >> $GITHUB_OUTPUT
 
       - name: Re-tag the image
-        run: docker tag ghcr.io/ricardo-campos-org/react-typescript-todolist/${{ matrix.image.service }}:candidate ghcr.io/ricardo-campos-org/react-typescript-todolist/${{ matrix.image.service }}:prod-${{ steps.inspect.outputs.source_pr }}
+        run: docker tag ghcr.io/ricardo-campos-org/react-typescript-todolist/${{ matrix.name }}:candidate ghcr.io/ricardo-campos-org/react-typescript-todolist/${{ matrix.name }}:prod-${{ steps.inspect.outputs.source_pr }}
 
       - name: Push new tag
-        run: docker push ghcr.io/ricardo-campos-org/react-typescript-todolist/${{ matrix.image.service }}:prod-${{ steps.inspect.outputs.source_pr }}
+        run: docker push ghcr.io/ricardo-campos-org/react-typescript-todolist/${{ matrix.name }}:prod-${{ steps.inspect.outputs.source_pr }}
+
+      - name: Update image tag to be deployed
+        uses: nick-fields/retry@v3.0.2
+        with:
+          timeout_minutes: 2
+          max_attempts: 3
+          command: |
+            response=$(curl -X POST \
+              "${DEPLOY_DOMAIN}/api/application.saveDockerProvider" \
+              --max-time 30 \
+              -H "accept: application/json" \
+              -H "x-api-key: ${API_KEY}" \
+              -H "Content-Type: application/json" \
+              -d "{\"applicationId\":\"${{ matrix.app_id }}" \
+                 ",\"dockerImage\"": ghcr.io/ricardo-campos-org/react-typescript-todolist/${{ matrix.name }}:prod-${{ steps.inspect.outputs.source_pr }}" \
+                 ",\"username\": \"${GHCR_USERNAME}\"" \
+                 ",\"password\": \"${GHCR_PASSWORD}\"" \
+                 ",\"registryUrl\": \"ghcr.io\"}" \
+              -w "\n%{http_code}" \
+              -s)
+
+            status_code=$(echo "$response" | tail -n1)
+            echo "Status code: $status_code"
+
+            if [ "$status_code" -ge 400 ]; then
+              body=$(echo "$response" | sed '$d')
+              
+              echo "Update failed with status code $status_code"
+              echo "Response body: $body"
+              exit 1
+            else
+              echo "Updated succeeded!"
+            fi
+
+      - name: Trigger Deployment
+        uses: nick-fields/retry@v3.0.2
+        with:
+          timeout_minutes: 2
+          max_attempts: 3
+          command: |
+            # wait 10 secs
+            sleep 10
+
+            response=$(curl -X POST \
+              "${DEPLOY_DOMAIN}/api/application.deploy" \
+              --max-time 30 \
+              -H "accept: application/json" \
+              -H "x-api-key: ${API_KEY}" \
+              -H "Content-Type: application/json" \
+              -d "{\"applicationId\":\"${{ matrix.app_id }}\"}" \
+              -w "\n%{http_code}" \
+              -s)
+
+            status_code=$(echo "$response" | tail -n1)
+            echo "Status code: $status_code"
+
+            if [ "$status_code" -ge 400 ]; then
+              body=$(echo "$response" | sed '$d')
+              
+              echo "Deployment failed with status code $status_code"
+              echo "Response body: $body"
+              exit 1
+            else
+              echo "Deployment succeeded!"
+            fi
+
+      - name: Verify deployment
+        run: |
+          # Wait for deployment to complete
+          sleep 30
+    
+          if ! curl -s -f "${{ matrix.health_check_url }}"; then
+            echo "Prod environment is not healthy"
+            exit 1
+          else
+            echo "Prod environment is healthy"
+          fi
