ci: split stage deploy into separate tasks to allow separate releases

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -103,6 +103,65 @@ jobs:
           cache-from: type=gha
           cache-to: type=gha,mode=max
 
+  client-stage-deployments:
+    name: Deploy Changes to Stage
+    runs-on: ubuntu-latest
+    needs: client-docker-build
+    if: github.event.pull_request.user.login == 'rmcampos' && github.event_name == 'pull_request'
+    env:
+      DEPLOY_DOMAIN: ${{ vars.DEPLOY_DOMAIN }}
+      API_KEY: ${{ secrets.DOKPLOY_API_KEY }}
+      CLIENT_APPID: ${{ secrets.STAGE_WEB_CLIENT_ID }}
+    steps:
+      - name: Pre-deployment check
+        run: |
+          if ! curl -s -f "${{ vars.CLIENT_STAGE_URL }}"; then
+            echo "Stage environment is not healthy"
+          else
+            echo "Stage environment is healthy"
+          fi
+
+      - name: Trigger Deployment
+        uses: nick-fields/retry@v3.0.2
+        with:
+          timeout_minutes: 2
+          max_attempts: 3
+          command: |
+            response=$(curl -X POST \
+              "${DEPLOY_DOMAIN}/api/application.deploy" \
+              --max-time 30 \
+              -H "accept: application/json" \
+              -H "x-api-key: ${API_KEY}" \
+              -H "Content-Type: application/json" \
+              -d "{\"applicationId\":\"${CLIENT_APPID}\"}" \
+              -w "\n%{http_code}" \
+              -s)
+
+            status_code=$(echo "$response" | tail -n1)
+            echo "Status code: $status_code"
+
+            if [ "$status_code" -ge 400 ]; then
+              body=$(echo "$response" | sed '$d')
+              
+              echo "Deployment failed with status code $status_code"
+              echo "Response body: $body"
+              exit 1
+            else
+              echo "Deployment succeeded!"
+            fi
+
+      - name: Verify deployment
+        run: |
+          # Wait for deployment to complete
+          sleep 30
+    
+          if ! curl -s -f "${{ vars.CLIENT_STAGE_URL }}"; then
+            echo "Stage environment is not healthy"
+            exit 1
+          else
+            echo "Stage environment is healthy"
+          fi
+
   java-code-checks:
     needs: changes
     if: ${{ needs.changes.outputs.server == 'true' }}
@@ -187,7 +246,7 @@ jobs:
           cache-from: type=gha
           cache-to: type=gha,mode=max
 
-  stage-deployments:
+  java-stage-deployments:
     name: Deploy Changes to Stage
     runs-on: ubuntu-latest
     needs: [java-docker-build, client-docker-build]
@@ -197,20 +256,10 @@ jobs:
       API_KEY: ${{ secrets.DOKPLOY_API_KEY }}
       SERVER_APPID: ${{ secrets.STAGE_API_CLIENT_ID }}
       CLIENT_APPID: ${{ secrets.STAGE_WEB_CLIENT_ID }}
-    strategy:
-      matrix:
-        name: [server, client]
-        include:
-          - name: server
-            health_check_url: "${{ vars.API_STAGE_URL }}/actuator/health"
-            app_id: ${SERVER_APPID}
-          - name: client
-            health_check_url: "${{ vars.CLIENT_STAGE_URL }}/"
-            app_id: ${CLIENT_APPID}
     steps:
       - name: Pre-deployment check
         run: |
-          if ! curl -s -f "${{ matrix.health_check_url }}"; then
+          if ! curl -s -f "${{ vars.API_STAGE_URL }}/actuator/health"; then
             echo "Stage environment is not healthy"
           else
             echo "Stage environment is healthy"
@@ -228,7 +277,7 @@ jobs:
               -H "accept: application/json" \
               -H "x-api-key: ${API_KEY}" \
               -H "Content-Type: application/json" \
-              -d "{\"applicationId\":\"${{ matrix.app_id }}\"}" \
+              -d "{\"applicationId\":\"${SERVER_APPID}\"}" \
               -w "\n%{http_code}" \
               -s)
 
@@ -250,7 +299,7 @@ jobs:
           # Wait for deployment to complete
           sleep 30
     
-          if ! curl -s -f "${{ matrix.health_check_url }}"; then
+          if ! curl -s -f "${{ vars.API_STAGE_URL }}/actuator/health"; then
             echo "Stage environment is not healthy"
             exit 1
           else
